print("hello man")
print("jai ho")
print("kin hai re tu")
print("sum kar")
print("i am from linux")
print("i am from kiit")
print("i am from patna")
print("i am from bihar")
print("my name is ")
print("hi")